// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../repository.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<String> initDatabase({required String dbPath}) =>
    RustLib.instance.api.crateApiSimpleInitDatabase(dbPath: dbPath);

Future<String> initDatabaseInMemory() =>
    RustLib.instance.api.crateApiSimpleInitDatabaseInMemory();

Future<List<NodeData>> getDueItems({
  required String userId,
  required int limit,
}) => RustLib.instance.api.crateApiSimpleGetDueItems(
  userId: userId,
  limit: limit,
);

Future<NodeData> getNodeData({required String nodeId}) =>
    RustLib.instance.api.crateApiSimpleGetNodeData(nodeId: nodeId);

Future<MemoryState> processReview({
  required String userId,
  required String nodeId,
  required ReviewGrade grade,
}) => RustLib.instance.api.crateApiSimpleProcessReview(
  userId: userId,
  nodeId: nodeId,
  grade: grade,
);
