// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Exercise {
  final String nodeId;
  final String arabic;
  final String translation;
  final String exerciseType;

  const Exercise({
    required this.nodeId,
    required this.arabic,
    required this.translation,
    required this.exerciseType,
  });

  @override
  int get hashCode =>
      nodeId.hashCode ^
      arabic.hashCode ^
      translation.hashCode ^
      exerciseType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Exercise &&
          runtimeType == other.runtimeType &&
          nodeId == other.nodeId &&
          arabic == other.arabic &&
          translation == other.translation &&
          exerciseType == other.exerciseType;
}
