// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'exercises.freezed.dart';

@freezed
sealed class Exercise with _$Exercise {
  const Exercise._();

  /// Simple recall: show Arabic, expect English meaning.
  const factory Exercise.recall({
    required String nodeId,
    required String arabic,
    required String translation,
  }) = Exercise_Recall;

  /// Simple cloze deletion from a verse.
  const factory Exercise.cloze({
    required String nodeId,
    required String question,
    required String answer,
  }) = Exercise_Cloze;

  /// Multiple-choice: Arabic prompt -> pick English
  const factory Exercise.mcqArToEn({
    required String nodeId,
    required String arabic,
    required String verseArabic,
    required int surahNumber,
    required int ayahNumber,
    required int wordIndex,
    required List<String> choicesEn,
    required int correctIndex,
  }) = Exercise_McqArToEn;

  /// Multiple-choice: English prompt -> pick Arabic
  const factory Exercise.mcqEnToAr({
    required String nodeId,
    required String english,
    required String verseArabic,
    required int surahNumber,
    required int ayahNumber,
    required int wordIndex,
    required List<String> choicesAr,
    required int correctIndex,
  }) = Exercise_McqEnToAr;
}
