// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AppStatePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcExerciseServicePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcExerciseService;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcLearningServicePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcLearningService;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcSessionServicePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionService;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcContentRepositoryPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynContentRepository;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcUserRepositoryPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynUserRepository;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  AppState
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    dynamic raw,
  );

  @protected
  ArcExerciseService
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcExerciseService(
    dynamic raw,
  );

  @protected
  ArcLearningService
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcLearningService(
    dynamic raw,
  );

  @protected
  ArcSessionService
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionService(
    dynamic raw,
  );

  @protected
  ArcContentRepository
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynContentRepository(
    dynamic raw,
  );

  @protected
  ArcUserRepository
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynUserRepository(
    dynamic raw,
  );

  @protected
  AppState
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    dynamic raw,
  );

  @protected
  AppState
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    dynamic raw,
  );

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  AppState
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    dynamic raw,
  );

  @protected
  ArcExerciseService
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcExerciseService(
    dynamic raw,
  );

  @protected
  ArcLearningService
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcLearningService(
    dynamic raw,
  );

  @protected
  ArcSessionService
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionService(
    dynamic raw,
  );

  @protected
  ArcContentRepository
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynContentRepository(
    dynamic raw,
  );

  @protected
  ArcUserRepository
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynUserRepository(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  EchoRecallMetricsDto dco_decode_box_autoadd_echo_recall_metrics_dto(
    dynamic raw,
  );

  @protected
  EchoRecallStateDto dco_decode_box_autoadd_echo_recall_state_dto(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  HintDto dco_decode_box_autoadd_hint_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  NodeData dco_decode_box_autoadd_node_data(dynamic raw);

  @protected
  NodeFilterDto dco_decode_box_autoadd_node_filter_dto(dynamic raw);

  @protected
  SessionDto dco_decode_box_autoadd_session_dto(dynamic raw);

  @protected
  SessionItemDto dco_decode_box_autoadd_session_item_dto(dynamic raw);

  @protected
  TranslatorDto dco_decode_box_autoadd_translator_dto(dynamic raw);

  @protected
  VerseDto dco_decode_box_autoadd_verse_dto(dynamic raw);

  @protected
  WordDto dco_decode_box_autoadd_word_dto(dynamic raw);

  @protected
  ContentPackageDto dco_decode_content_package_dto(dynamic raw);

  @protected
  DashboardStatsDto dco_decode_dashboard_stats_dto(dynamic raw);

  @protected
  DbHealthDto dco_decode_db_health_dto(dynamic raw);

  @protected
  DbQueryResultDto dco_decode_db_query_result_dto(dynamic raw);

  @protected
  DebugStatsDto dco_decode_debug_stats_dto(dynamic raw);

  @protected
  EchoRecallMetricsDto dco_decode_echo_recall_metrics_dto(dynamic raw);

  @protected
  EchoRecallResultDto dco_decode_echo_recall_result_dto(dynamic raw);

  @protected
  EchoRecallStateDto dco_decode_echo_recall_state_dto(dynamic raw);

  @protected
  EchoRecallStatsDto dco_decode_echo_recall_stats_dto(dynamic raw);

  @protected
  EchoRecallWordDto dco_decode_echo_recall_word_dto(dynamic raw);

  @protected
  EnergySnapshotDto dco_decode_energy_snapshot_dto(dynamic raw);

  @protected
  EnergyUpdateDto dco_decode_energy_update_dto(dynamic raw);

  @protected
  ExerciseDataDto dco_decode_exercise_data_dto(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  HintDto dco_decode_hint_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  InstalledPackageDto dco_decode_installed_package_dto(dynamic raw);

  @protected
  LanguageDto dco_decode_language_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ContentPackageDto> dco_decode_list_content_package_dto(dynamic raw);

  @protected
  List<EchoRecallWordDto> dco_decode_list_echo_recall_word_dto(dynamic raw);

  @protected
  List<EnergyUpdateDto> dco_decode_list_energy_update_dto(dynamic raw);

  @protected
  List<ExerciseDataDto> dco_decode_list_exercise_data_dto(dynamic raw);

  @protected
  List<InstalledPackageDto> dco_decode_list_installed_package_dto(dynamic raw);

  @protected
  List<LanguageDto> dco_decode_list_language_dto(dynamic raw);

  @protected
  List<List<String>> dco_decode_list_list_String(dynamic raw);

  @protected
  List<NodeEnergyDto> dco_decode_list_node_energy_dto(dynamic raw);

  @protected
  List<NodeSearchDto> dco_decode_list_node_search_dto(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<SessionPreviewDto> dco_decode_list_session_preview_dto(dynamic raw);

  @protected
  List<SurahInfo> dco_decode_list_surah_info(dynamic raw);

  @protected
  List<TranslatorDto> dco_decode_list_translator_dto(dynamic raw);

  @protected
  List<WordDto> dco_decode_list_word_dto(dynamic raw);

  @protected
  List<WordTimingDto> dco_decode_list_word_timing_dto(dynamic raw);

  @protected
  NodeData dco_decode_node_data(dynamic raw);

  @protected
  NodeEnergyDto dco_decode_node_energy_dto(dynamic raw);

  @protected
  NodeFilterDto dco_decode_node_filter_dto(dynamic raw);

  @protected
  NodeSearchDto dco_decode_node_search_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  HintDto? dco_decode_opt_box_autoadd_hint_dto(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  NodeData? dco_decode_opt_box_autoadd_node_data(dynamic raw);

  @protected
  SessionDto? dco_decode_opt_box_autoadd_session_dto(dynamic raw);

  @protected
  SessionItemDto? dco_decode_opt_box_autoadd_session_item_dto(dynamic raw);

  @protected
  TranslatorDto? dco_decode_opt_box_autoadd_translator_dto(dynamic raw);

  @protected
  VerseDto? dco_decode_opt_box_autoadd_verse_dto(dynamic raw);

  @protected
  WordDto? dco_decode_opt_box_autoadd_word_dto(dynamic raw);

  @protected
  PropagationDiagnosticsDto dco_decode_propagation_diagnostics_dto(dynamic raw);

  @protected
  PropagationResultDto dco_decode_propagation_result_dto(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  SessionDto dco_decode_session_dto(dynamic raw);

  @protected
  SessionItemDto dco_decode_session_item_dto(dynamic raw);

  @protected
  SessionPreviewDto dco_decode_session_preview_dto(dynamic raw);

  @protected
  SessionSummaryDto dco_decode_session_summary_dto(dynamic raw);

  @protected
  SurahInfo dco_decode_surah_info(dynamic raw);

  @protected
  TranslatorDto dco_decode_translator_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VerseDto dco_decode_verse_dto(dynamic raw);

  @protected
  WordDto dco_decode_word_dto(dynamic raw);

  @protected
  WordTimingDto dco_decode_word_timing_dto(dynamic raw);

  @protected
  WordVisibilityDto dco_decode_word_visibility_dto(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  AppState
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    SseDeserializer deserializer,
  );

  @protected
  ArcExerciseService
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcExerciseService(
    SseDeserializer deserializer,
  );

  @protected
  ArcLearningService
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcLearningService(
    SseDeserializer deserializer,
  );

  @protected
  ArcSessionService
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionService(
    SseDeserializer deserializer,
  );

  @protected
  ArcContentRepository
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynContentRepository(
    SseDeserializer deserializer,
  );

  @protected
  ArcUserRepository
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynUserRepository(
    SseDeserializer deserializer,
  );

  @protected
  AppState
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    SseDeserializer deserializer,
  );

  @protected
  AppState
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  AppState
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    SseDeserializer deserializer,
  );

  @protected
  ArcExerciseService
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcExerciseService(
    SseDeserializer deserializer,
  );

  @protected
  ArcLearningService
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcLearningService(
    SseDeserializer deserializer,
  );

  @protected
  ArcSessionService
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionService(
    SseDeserializer deserializer,
  );

  @protected
  ArcContentRepository
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynContentRepository(
    SseDeserializer deserializer,
  );

  @protected
  ArcUserRepository
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynUserRepository(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  EchoRecallMetricsDto sse_decode_box_autoadd_echo_recall_metrics_dto(
    SseDeserializer deserializer,
  );

  @protected
  EchoRecallStateDto sse_decode_box_autoadd_echo_recall_state_dto(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  HintDto sse_decode_box_autoadd_hint_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  NodeData sse_decode_box_autoadd_node_data(SseDeserializer deserializer);

  @protected
  NodeFilterDto sse_decode_box_autoadd_node_filter_dto(
    SseDeserializer deserializer,
  );

  @protected
  SessionDto sse_decode_box_autoadd_session_dto(SseDeserializer deserializer);

  @protected
  SessionItemDto sse_decode_box_autoadd_session_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  TranslatorDto sse_decode_box_autoadd_translator_dto(
    SseDeserializer deserializer,
  );

  @protected
  VerseDto sse_decode_box_autoadd_verse_dto(SseDeserializer deserializer);

  @protected
  WordDto sse_decode_box_autoadd_word_dto(SseDeserializer deserializer);

  @protected
  ContentPackageDto sse_decode_content_package_dto(
    SseDeserializer deserializer,
  );

  @protected
  DashboardStatsDto sse_decode_dashboard_stats_dto(
    SseDeserializer deserializer,
  );

  @protected
  DbHealthDto sse_decode_db_health_dto(SseDeserializer deserializer);

  @protected
  DbQueryResultDto sse_decode_db_query_result_dto(SseDeserializer deserializer);

  @protected
  DebugStatsDto sse_decode_debug_stats_dto(SseDeserializer deserializer);

  @protected
  EchoRecallMetricsDto sse_decode_echo_recall_metrics_dto(
    SseDeserializer deserializer,
  );

  @protected
  EchoRecallResultDto sse_decode_echo_recall_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  EchoRecallStateDto sse_decode_echo_recall_state_dto(
    SseDeserializer deserializer,
  );

  @protected
  EchoRecallStatsDto sse_decode_echo_recall_stats_dto(
    SseDeserializer deserializer,
  );

  @protected
  EchoRecallWordDto sse_decode_echo_recall_word_dto(
    SseDeserializer deserializer,
  );

  @protected
  EnergySnapshotDto sse_decode_energy_snapshot_dto(
    SseDeserializer deserializer,
  );

  @protected
  EnergyUpdateDto sse_decode_energy_update_dto(SseDeserializer deserializer);

  @protected
  ExerciseDataDto sse_decode_exercise_data_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  HintDto sse_decode_hint_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  InstalledPackageDto sse_decode_installed_package_dto(
    SseDeserializer deserializer,
  );

  @protected
  LanguageDto sse_decode_language_dto(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ContentPackageDto> sse_decode_list_content_package_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<EchoRecallWordDto> sse_decode_list_echo_recall_word_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<EnergyUpdateDto> sse_decode_list_energy_update_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ExerciseDataDto> sse_decode_list_exercise_data_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<InstalledPackageDto> sse_decode_list_installed_package_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<LanguageDto> sse_decode_list_language_dto(SseDeserializer deserializer);

  @protected
  List<List<String>> sse_decode_list_list_String(SseDeserializer deserializer);

  @protected
  List<NodeEnergyDto> sse_decode_list_node_energy_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<NodeSearchDto> sse_decode_list_node_search_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<SessionPreviewDto> sse_decode_list_session_preview_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<SurahInfo> sse_decode_list_surah_info(SseDeserializer deserializer);

  @protected
  List<TranslatorDto> sse_decode_list_translator_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<WordDto> sse_decode_list_word_dto(SseDeserializer deserializer);

  @protected
  List<WordTimingDto> sse_decode_list_word_timing_dto(
    SseDeserializer deserializer,
  );

  @protected
  NodeData sse_decode_node_data(SseDeserializer deserializer);

  @protected
  NodeEnergyDto sse_decode_node_energy_dto(SseDeserializer deserializer);

  @protected
  NodeFilterDto sse_decode_node_filter_dto(SseDeserializer deserializer);

  @protected
  NodeSearchDto sse_decode_node_search_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  HintDto? sse_decode_opt_box_autoadd_hint_dto(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  NodeData? sse_decode_opt_box_autoadd_node_data(SseDeserializer deserializer);

  @protected
  SessionDto? sse_decode_opt_box_autoadd_session_dto(
    SseDeserializer deserializer,
  );

  @protected
  SessionItemDto? sse_decode_opt_box_autoadd_session_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  TranslatorDto? sse_decode_opt_box_autoadd_translator_dto(
    SseDeserializer deserializer,
  );

  @protected
  VerseDto? sse_decode_opt_box_autoadd_verse_dto(SseDeserializer deserializer);

  @protected
  WordDto? sse_decode_opt_box_autoadd_word_dto(SseDeserializer deserializer);

  @protected
  PropagationDiagnosticsDto sse_decode_propagation_diagnostics_dto(
    SseDeserializer deserializer,
  );

  @protected
  PropagationResultDto sse_decode_propagation_result_dto(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  SessionDto sse_decode_session_dto(SseDeserializer deserializer);

  @protected
  SessionItemDto sse_decode_session_item_dto(SseDeserializer deserializer);

  @protected
  SessionPreviewDto sse_decode_session_preview_dto(
    SseDeserializer deserializer,
  );

  @protected
  SessionSummaryDto sse_decode_session_summary_dto(
    SseDeserializer deserializer,
  );

  @protected
  SurahInfo sse_decode_surah_info(SseDeserializer deserializer);

  @protected
  TranslatorDto sse_decode_translator_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VerseDto sse_decode_verse_dto(SseDeserializer deserializer);

  @protected
  WordDto sse_decode_word_dto(SseDeserializer deserializer);

  @protected
  WordTimingDto sse_decode_word_timing_dto(SseDeserializer deserializer);

  @protected
  WordVisibilityDto sse_decode_word_visibility_dto(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    AppState self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcExerciseService(
    ArcExerciseService self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcLearningService(
    ArcLearningService self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionService(
    ArcSessionService self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynContentRepository(
    ArcContentRepository self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynUserRepository(
    ArcUserRepository self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    AppState self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    AppState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    AppState self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcExerciseService(
    ArcExerciseService self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcLearningService(
    ArcLearningService self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionService(
    ArcSessionService self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynContentRepository(
    ArcContentRepository self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynUserRepository(
    ArcUserRepository self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_echo_recall_metrics_dto(
    EchoRecallMetricsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_echo_recall_state_dto(
    EchoRecallStateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_hint_dto(HintDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_node_data(
    NodeData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_node_filter_dto(
    NodeFilterDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_session_dto(
    SessionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_session_item_dto(
    SessionItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_translator_dto(
    TranslatorDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_verse_dto(
    VerseDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_word_dto(WordDto self, SseSerializer serializer);

  @protected
  void sse_encode_content_package_dto(
    ContentPackageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dashboard_stats_dto(
    DashboardStatsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_db_health_dto(DbHealthDto self, SseSerializer serializer);

  @protected
  void sse_encode_db_query_result_dto(
    DbQueryResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_debug_stats_dto(DebugStatsDto self, SseSerializer serializer);

  @protected
  void sse_encode_echo_recall_metrics_dto(
    EchoRecallMetricsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_echo_recall_result_dto(
    EchoRecallResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_echo_recall_state_dto(
    EchoRecallStateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_echo_recall_stats_dto(
    EchoRecallStatsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_echo_recall_word_dto(
    EchoRecallWordDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_energy_snapshot_dto(
    EnergySnapshotDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_energy_update_dto(
    EnergyUpdateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_exercise_data_dto(
    ExerciseDataDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_hint_dto(HintDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_installed_package_dto(
    InstalledPackageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_language_dto(LanguageDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_content_package_dto(
    List<ContentPackageDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_echo_recall_word_dto(
    List<EchoRecallWordDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_energy_update_dto(
    List<EnergyUpdateDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_exercise_data_dto(
    List<ExerciseDataDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_installed_package_dto(
    List<InstalledPackageDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_language_dto(
    List<LanguageDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_String(
    List<List<String>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_node_energy_dto(
    List<NodeEnergyDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_node_search_dto(
    List<NodeSearchDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_session_preview_dto(
    List<SessionPreviewDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_surah_info(
    List<SurahInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_translator_dto(
    List<TranslatorDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_word_dto(List<WordDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_word_timing_dto(
    List<WordTimingDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_node_data(NodeData self, SseSerializer serializer);

  @protected
  void sse_encode_node_energy_dto(NodeEnergyDto self, SseSerializer serializer);

  @protected
  void sse_encode_node_filter_dto(NodeFilterDto self, SseSerializer serializer);

  @protected
  void sse_encode_node_search_dto(NodeSearchDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_hint_dto(
    HintDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_node_data(
    NodeData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_session_dto(
    SessionDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_session_item_dto(
    SessionItemDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_translator_dto(
    TranslatorDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_verse_dto(
    VerseDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_word_dto(
    WordDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_propagation_diagnostics_dto(
    PropagationDiagnosticsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_propagation_result_dto(
    PropagationResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_dto(SessionDto self, SseSerializer serializer);

  @protected
  void sse_encode_session_item_dto(
    SessionItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_preview_dto(
    SessionPreviewDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_summary_dto(
    SessionSummaryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_surah_info(SurahInfo self, SseSerializer serializer);

  @protected
  void sse_encode_translator_dto(TranslatorDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_verse_dto(VerseDto self, SseSerializer serializer);

  @protected
  void sse_encode_word_dto(WordDto self, SseSerializer serializer);

  @protected
  void sse_encode_word_timing_dto(WordTimingDto self, SseSerializer serializer);

  @protected
  void sse_encode_word_visibility_dto(
    WordVisibilityDto self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcExerciseService(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcExerciseService(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcExerciseService(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcExerciseService(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcLearningService(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcLearningService(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcLearningService(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcLearningService(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionService(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionService(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionService(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionService(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynContentRepository(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynContentRepository(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynContentRepository(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynContentRepository(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynUserRepository(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynUserRepository(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynUserRepository(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynUserRepository(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcExerciseService(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcExerciseService(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcLearningService(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcLearningService(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionService(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionService(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynContentRepository(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynContentRepository(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynUserRepository(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynUserRepository(
    int ptr,
  );
}
