// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'exercises.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'repository.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 554516516;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_iqrah',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<DebugStats> crateApiGetDebugStats({required String userId});

  Future<List<Exercise>> crateApiGetExercises({
    required String userId,
    required int limit,
  });

  Future<List<ItemPreview>> crateApiGetSessionPreview({
    required String userId,
    required int limit,
  });

  Future<void> crateApiInitApp();

  Future<MemoryState> crateApiProcessReview({
    required String userId,
    required String nodeId,
    required ReviewGrade grade,
  });

  Future<String> crateApiRefreshPriorityScores({required String userId});

  Future<String> crateApiReseedDatabase();

  Future<String> crateApiSetupDatabase({
    String? dbPath,
    required List<int> kgBytes,
  });

  Future<String> crateApiSetupDatabaseInMemory({required List<int> kgBytes});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<DebugStats> crateApiGetDebugStats({required String userId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(userId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_debug_stats,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGetDebugStatsConstMeta,
        argValues: [userId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetDebugStatsConstMeta =>
      const TaskConstMeta(debugName: "get_debug_stats", argNames: ["userId"]);

  @override
  Future<List<Exercise>> crateApiGetExercises({
    required String userId,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(userId, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_exercise,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGetExercisesConstMeta,
        argValues: [userId, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetExercisesConstMeta => const TaskConstMeta(
    debugName: "get_exercises",
    argNames: ["userId", "limit"],
  );

  @override
  Future<List<ItemPreview>> crateApiGetSessionPreview({
    required String userId,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(userId, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_item_preview,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGetSessionPreviewConstMeta,
        argValues: [userId, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetSessionPreviewConstMeta => const TaskConstMeta(
    debugName: "get_session_preview",
    argNames: ["userId", "limit"],
  );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<MemoryState> crateApiProcessReview({
    required String userId,
    required String nodeId,
    required ReviewGrade grade,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(userId, serializer);
          sse_encode_String(nodeId, serializer);
          sse_encode_review_grade(grade, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_memory_state,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiProcessReviewConstMeta,
        argValues: [userId, nodeId, grade],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProcessReviewConstMeta => const TaskConstMeta(
    debugName: "process_review",
    argNames: ["userId", "nodeId", "grade"],
  );

  @override
  Future<String> crateApiRefreshPriorityScores({required String userId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(userId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRefreshPriorityScoresConstMeta,
        argValues: [userId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRefreshPriorityScoresConstMeta =>
      const TaskConstMeta(
        debugName: "refresh_priority_scores",
        argNames: ["userId"],
      );

  @override
  Future<String> crateApiReseedDatabase() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiReseedDatabaseConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReseedDatabaseConstMeta =>
      const TaskConstMeta(debugName: "reseed_database", argNames: []);

  @override
  Future<String> crateApiSetupDatabase({
    String? dbPath,
    required List<int> kgBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(dbPath, serializer);
          sse_encode_list_prim_u_8_loose(kgBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSetupDatabaseConstMeta,
        argValues: [dbPath, kgBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetupDatabaseConstMeta => const TaskConstMeta(
    debugName: "setup_database",
    argNames: ["dbPath", "kgBytes"],
  );

  @override
  Future<String> crateApiSetupDatabaseInMemory({required List<int> kgBytes}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(kgBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSetupDatabaseInMemoryConstMeta,
        argValues: [kgBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetupDatabaseInMemoryConstMeta =>
      const TaskConstMeta(
        debugName: "setup_database_in_memory",
        argNames: ["kgBytes"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  DebugStats dco_decode_debug_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return DebugStats(
      dueToday: dco_decode_u_32(arr[0]),
      totalReviewed: dco_decode_u_32(arr[1]),
      avgEnergy: dco_decode_f_64(arr[2]),
      nextDueItems: dco_decode_list_due_item(arr[3]),
      totalNodesCount: dco_decode_usize(arr[4]),
      totalEdgesCount: dco_decode_usize(arr[5]),
    );
  }

  @protected
  DueItem dco_decode_due_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DueItem(
      nodeId: dco_decode_String(arr[0]),
      arabic: dco_decode_opt_String(arr[1]),
      state: dco_decode_memory_state(arr[2]),
    );
  }

  @protected
  Exercise dco_decode_exercise(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Exercise(
      nodeId: dco_decode_String(arr[0]),
      arabic: dco_decode_String(arr[1]),
      translation: dco_decode_String(arr[2]),
      exerciseType: dco_decode_String(arr[3]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  ItemPreview dco_decode_item_preview(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ItemPreview(
      nodeId: dco_decode_String(arr[0]),
      arabic: dco_decode_opt_String(arr[1]),
      translation: dco_decode_opt_String(arr[2]),
      priorityScore: dco_decode_f_64(arr[3]),
      scoreBreakdown: dco_decode_score_breakdown(arr[4]),
    );
  }

  @protected
  List<DueItem> dco_decode_list_due_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_due_item).toList();
  }

  @protected
  List<Exercise> dco_decode_list_exercise(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_exercise).toList();
  }

  @protected
  List<ItemPreview> dco_decode_list_item_preview(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_item_preview).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MemoryState dco_decode_memory_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return MemoryState(
      stability: dco_decode_f_64(arr[0]),
      difficulty: dco_decode_f_64(arr[1]),
      energy: dco_decode_f_64(arr[2]),
      lastReviewed: dco_decode_i_64(arr[3]),
      dueAt: dco_decode_i_64(arr[4]),
      reviewCount: dco_decode_i_32(arr[5]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ReviewGrade dco_decode_review_grade(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ReviewGrade.values[raw as int];
  }

  @protected
  ScoreBreakdown dco_decode_score_breakdown(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ScoreBreakdown(
      daysOverdue: dco_decode_f_64(arr[0]),
      masteryGap: dco_decode_f_64(arr[1]),
      importance: dco_decode_f_64(arr[2]),
      weights: dco_decode_score_weights(arr[3]),
    );
  }

  @protected
  ScoreWeights dco_decode_score_weights(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ScoreWeights(
      wDue: dco_decode_f_64(arr[0]),
      wNeed: dco_decode_f_64(arr[1]),
      wYield: dco_decode_f_64(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  DebugStats sse_decode_debug_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_dueToday = sse_decode_u_32(deserializer);
    var var_totalReviewed = sse_decode_u_32(deserializer);
    var var_avgEnergy = sse_decode_f_64(deserializer);
    var var_nextDueItems = sse_decode_list_due_item(deserializer);
    var var_totalNodesCount = sse_decode_usize(deserializer);
    var var_totalEdgesCount = sse_decode_usize(deserializer);
    return DebugStats(
      dueToday: var_dueToday,
      totalReviewed: var_totalReviewed,
      avgEnergy: var_avgEnergy,
      nextDueItems: var_nextDueItems,
      totalNodesCount: var_totalNodesCount,
      totalEdgesCount: var_totalEdgesCount,
    );
  }

  @protected
  DueItem sse_decode_due_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nodeId = sse_decode_String(deserializer);
    var var_arabic = sse_decode_opt_String(deserializer);
    var var_state = sse_decode_memory_state(deserializer);
    return DueItem(nodeId: var_nodeId, arabic: var_arabic, state: var_state);
  }

  @protected
  Exercise sse_decode_exercise(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nodeId = sse_decode_String(deserializer);
    var var_arabic = sse_decode_String(deserializer);
    var var_translation = sse_decode_String(deserializer);
    var var_exerciseType = sse_decode_String(deserializer);
    return Exercise(
      nodeId: var_nodeId,
      arabic: var_arabic,
      translation: var_translation,
      exerciseType: var_exerciseType,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  ItemPreview sse_decode_item_preview(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nodeId = sse_decode_String(deserializer);
    var var_arabic = sse_decode_opt_String(deserializer);
    var var_translation = sse_decode_opt_String(deserializer);
    var var_priorityScore = sse_decode_f_64(deserializer);
    var var_scoreBreakdown = sse_decode_score_breakdown(deserializer);
    return ItemPreview(
      nodeId: var_nodeId,
      arabic: var_arabic,
      translation: var_translation,
      priorityScore: var_priorityScore,
      scoreBreakdown: var_scoreBreakdown,
    );
  }

  @protected
  List<DueItem> sse_decode_list_due_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DueItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_due_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<Exercise> sse_decode_list_exercise(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Exercise>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_exercise(deserializer));
    }
    return ans_;
  }

  @protected
  List<ItemPreview> sse_decode_list_item_preview(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ItemPreview>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_item_preview(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MemoryState sse_decode_memory_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_stability = sse_decode_f_64(deserializer);
    var var_difficulty = sse_decode_f_64(deserializer);
    var var_energy = sse_decode_f_64(deserializer);
    var var_lastReviewed = sse_decode_i_64(deserializer);
    var var_dueAt = sse_decode_i_64(deserializer);
    var var_reviewCount = sse_decode_i_32(deserializer);
    return MemoryState(
      stability: var_stability,
      difficulty: var_difficulty,
      energy: var_energy,
      lastReviewed: var_lastReviewed,
      dueAt: var_dueAt,
      reviewCount: var_reviewCount,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ReviewGrade sse_decode_review_grade(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ReviewGrade.values[inner];
  }

  @protected
  ScoreBreakdown sse_decode_score_breakdown(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_daysOverdue = sse_decode_f_64(deserializer);
    var var_masteryGap = sse_decode_f_64(deserializer);
    var var_importance = sse_decode_f_64(deserializer);
    var var_weights = sse_decode_score_weights(deserializer);
    return ScoreBreakdown(
      daysOverdue: var_daysOverdue,
      masteryGap: var_masteryGap,
      importance: var_importance,
      weights: var_weights,
    );
  }

  @protected
  ScoreWeights sse_decode_score_weights(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_wDue = sse_decode_f_64(deserializer);
    var var_wNeed = sse_decode_f_64(deserializer);
    var var_wYield = sse_decode_f_64(deserializer);
    return ScoreWeights(wDue: var_wDue, wNeed: var_wNeed, wYield: var_wYield);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_debug_stats(DebugStats self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.dueToday, serializer);
    sse_encode_u_32(self.totalReviewed, serializer);
    sse_encode_f_64(self.avgEnergy, serializer);
    sse_encode_list_due_item(self.nextDueItems, serializer);
    sse_encode_usize(self.totalNodesCount, serializer);
    sse_encode_usize(self.totalEdgesCount, serializer);
  }

  @protected
  void sse_encode_due_item(DueItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.nodeId, serializer);
    sse_encode_opt_String(self.arabic, serializer);
    sse_encode_memory_state(self.state, serializer);
  }

  @protected
  void sse_encode_exercise(Exercise self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.nodeId, serializer);
    sse_encode_String(self.arabic, serializer);
    sse_encode_String(self.translation, serializer);
    sse_encode_String(self.exerciseType, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_item_preview(ItemPreview self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.nodeId, serializer);
    sse_encode_opt_String(self.arabic, serializer);
    sse_encode_opt_String(self.translation, serializer);
    sse_encode_f_64(self.priorityScore, serializer);
    sse_encode_score_breakdown(self.scoreBreakdown, serializer);
  }

  @protected
  void sse_encode_list_due_item(List<DueItem> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_due_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_exercise(List<Exercise> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_exercise(item, serializer);
    }
  }

  @protected
  void sse_encode_list_item_preview(
    List<ItemPreview> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_item_preview(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_memory_state(MemoryState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.stability, serializer);
    sse_encode_f_64(self.difficulty, serializer);
    sse_encode_f_64(self.energy, serializer);
    sse_encode_i_64(self.lastReviewed, serializer);
    sse_encode_i_64(self.dueAt, serializer);
    sse_encode_i_32(self.reviewCount, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_review_grade(ReviewGrade self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_score_breakdown(
    ScoreBreakdown self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.daysOverdue, serializer);
    sse_encode_f_64(self.masteryGap, serializer);
    sse_encode_f_64(self.importance, serializer);
    sse_encode_score_weights(self.weights, serializer);
  }

  @protected
  void sse_encode_score_weights(ScoreWeights self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.wDue, serializer);
    sse_encode_f_64(self.wNeed, serializer);
    sse_encode_f_64(self.wYield, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
