// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 2047187040;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'iqrah_api',
        ioDirectory: 'rust/crates/iqrah-api/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  ArcContentRepository crateApiAppStateAutoAccessorGetContentRepo({
    required AppState that,
  });

  ArcLearningService crateApiAppStateAutoAccessorGetLearningService({
    required AppState that,
  });

  ArcSessionService crateApiAppStateAutoAccessorGetSessionService({
    required AppState that,
  });

  ArcUserRepository crateApiAppStateAutoAccessorGetUserRepo({
    required AppState that,
  });

  void crateApiAppStateAutoAccessorSetContentRepo({
    required AppState that,
    required ArcContentRepository contentRepo,
  });

  void crateApiAppStateAutoAccessorSetLearningService({
    required AppState that,
    required ArcLearningService learningService,
  });

  void crateApiAppStateAutoAccessorSetSessionService({
    required AppState that,
    required ArcSessionService sessionService,
  });

  void crateApiAppStateAutoAccessorSetUserRepo({
    required AppState that,
    required ArcUserRepository userRepo,
  });

  Future<String> crateApiClearSession();

  Future<List<SurahInfo>> crateApiGetAvailableSurahs();

  Future<DashboardStatsDto> crateApiGetDashboardStats({required String userId});

  Future<DebugStatsDto> crateApiGetDebugStats({required String userId});

  Future<List<ExerciseDto>> crateApiGetExercises({
    required String userId,
    required int limit,
    int? surahFilter,
    required bool isHighYield,
  });

  Future<List<SessionPreviewDto>> crateApiGetSessionPreview({
    required String userId,
    required int limit,
    required bool isHighYield,
  });

  Future<void> crateApiInitApp();

  Future<String> crateApiProcessReview({
    required String userId,
    required String nodeId,
    required int grade,
  });

  Future<String> crateApiReseedDatabase({required String userId});

  Future<List<NodeSearchDto>> crateApiSearchNodes({
    required String query,
    required int limit,
  });

  Future<String> crateApiSetupDatabase({
    required String contentDbPath,
    required String userDbPath,
    required List<int> kgBytes,
  });

  Future<String> crateApiSetupDatabaseInMemory({required List<int> kgBytes});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AppState;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AppState;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_AppStatePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ArcLearningService;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ArcLearningService;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcLearningServicePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ArcSessionService;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ArcSessionService;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcSessionServicePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ArcContentRepository;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ArcContentRepository;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcContentRepositoryPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ArcUserRepository;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ArcUserRepository;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcUserRepositoryPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  ArcContentRepository crateApiAppStateAutoAccessorGetContentRepo({
    required AppState that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynContentRepository,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppStateAutoAccessorGetContentRepoConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppStateAutoAccessorGetContentRepoConstMeta =>
      const TaskConstMeta(
        debugName: "AppState_auto_accessor_get_content_repo",
        argNames: ["that"],
      );

  @override
  ArcLearningService crateApiAppStateAutoAccessorGetLearningService({
    required AppState that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcLearningService,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppStateAutoAccessorGetLearningServiceConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppStateAutoAccessorGetLearningServiceConstMeta =>
      const TaskConstMeta(
        debugName: "AppState_auto_accessor_get_learning_service",
        argNames: ["that"],
      );

  @override
  ArcSessionService crateApiAppStateAutoAccessorGetSessionService({
    required AppState that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionService,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppStateAutoAccessorGetSessionServiceConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppStateAutoAccessorGetSessionServiceConstMeta =>
      const TaskConstMeta(
        debugName: "AppState_auto_accessor_get_session_service",
        argNames: ["that"],
      );

  @override
  ArcUserRepository crateApiAppStateAutoAccessorGetUserRepo({
    required AppState that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynUserRepository,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppStateAutoAccessorGetUserRepoConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppStateAutoAccessorGetUserRepoConstMeta =>
      const TaskConstMeta(
        debugName: "AppState_auto_accessor_get_user_repo",
        argNames: ["that"],
      );

  @override
  void crateApiAppStateAutoAccessorSetContentRepo({
    required AppState that,
    required ArcContentRepository contentRepo,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
            that,
            serializer,
          );
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynContentRepository(
            contentRepo,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppStateAutoAccessorSetContentRepoConstMeta,
        argValues: [that, contentRepo],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppStateAutoAccessorSetContentRepoConstMeta =>
      const TaskConstMeta(
        debugName: "AppState_auto_accessor_set_content_repo",
        argNames: ["that", "contentRepo"],
      );

  @override
  void crateApiAppStateAutoAccessorSetLearningService({
    required AppState that,
    required ArcLearningService learningService,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
            that,
            serializer,
          );
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcLearningService(
            learningService,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppStateAutoAccessorSetLearningServiceConstMeta,
        argValues: [that, learningService],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppStateAutoAccessorSetLearningServiceConstMeta =>
      const TaskConstMeta(
        debugName: "AppState_auto_accessor_set_learning_service",
        argNames: ["that", "learningService"],
      );

  @override
  void crateApiAppStateAutoAccessorSetSessionService({
    required AppState that,
    required ArcSessionService sessionService,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
            that,
            serializer,
          );
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionService(
            sessionService,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppStateAutoAccessorSetSessionServiceConstMeta,
        argValues: [that, sessionService],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppStateAutoAccessorSetSessionServiceConstMeta =>
      const TaskConstMeta(
        debugName: "AppState_auto_accessor_set_session_service",
        argNames: ["that", "sessionService"],
      );

  @override
  void crateApiAppStateAutoAccessorSetUserRepo({
    required AppState that,
    required ArcUserRepository userRepo,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
            that,
            serializer,
          );
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynUserRepository(
            userRepo,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAppStateAutoAccessorSetUserRepoConstMeta,
        argValues: [that, userRepo],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAppStateAutoAccessorSetUserRepoConstMeta =>
      const TaskConstMeta(
        debugName: "AppState_auto_accessor_set_user_repo",
        argNames: ["that", "userRepo"],
      );

  @override
  Future<String> crateApiClearSession() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiClearSessionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClearSessionConstMeta =>
      const TaskConstMeta(debugName: "clear_session", argNames: []);

  @override
  Future<List<SurahInfo>> crateApiGetAvailableSurahs() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_surah_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGetAvailableSurahsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetAvailableSurahsConstMeta =>
      const TaskConstMeta(debugName: "get_available_surahs", argNames: []);

  @override
  Future<DashboardStatsDto> crateApiGetDashboardStats({
    required String userId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(userId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_dashboard_stats_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGetDashboardStatsConstMeta,
        argValues: [userId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetDashboardStatsConstMeta => const TaskConstMeta(
    debugName: "get_dashboard_stats",
    argNames: ["userId"],
  );

  @override
  Future<DebugStatsDto> crateApiGetDebugStats({required String userId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(userId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_debug_stats_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGetDebugStatsConstMeta,
        argValues: [userId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetDebugStatsConstMeta =>
      const TaskConstMeta(debugName: "get_debug_stats", argNames: ["userId"]);

  @override
  Future<List<ExerciseDto>> crateApiGetExercises({
    required String userId,
    required int limit,
    int? surahFilter,
    required bool isHighYield,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(userId, serializer);
          sse_encode_u_32(limit, serializer);
          sse_encode_opt_box_autoadd_i_32(surahFilter, serializer);
          sse_encode_bool(isHighYield, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_exercise_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGetExercisesConstMeta,
        argValues: [userId, limit, surahFilter, isHighYield],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetExercisesConstMeta => const TaskConstMeta(
    debugName: "get_exercises",
    argNames: ["userId", "limit", "surahFilter", "isHighYield"],
  );

  @override
  Future<List<SessionPreviewDto>> crateApiGetSessionPreview({
    required String userId,
    required int limit,
    required bool isHighYield,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(userId, serializer);
          sse_encode_u_32(limit, serializer);
          sse_encode_bool(isHighYield, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_session_preview_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGetSessionPreviewConstMeta,
        argValues: [userId, limit, isHighYield],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetSessionPreviewConstMeta => const TaskConstMeta(
    debugName: "get_session_preview",
    argNames: ["userId", "limit", "isHighYield"],
  );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<String> crateApiProcessReview({
    required String userId,
    required String nodeId,
    required int grade,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(userId, serializer);
          sse_encode_String(nodeId, serializer);
          sse_encode_u_8(grade, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiProcessReviewConstMeta,
        argValues: [userId, nodeId, grade],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProcessReviewConstMeta => const TaskConstMeta(
    debugName: "process_review",
    argNames: ["userId", "nodeId", "grade"],
  );

  @override
  Future<String> crateApiReseedDatabase({required String userId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(userId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiReseedDatabaseConstMeta,
        argValues: [userId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReseedDatabaseConstMeta =>
      const TaskConstMeta(debugName: "reseed_database", argNames: ["userId"]);

  @override
  Future<List<NodeSearchDto>> crateApiSearchNodes({
    required String query,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_node_search_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSearchNodesConstMeta,
        argValues: [query, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSearchNodesConstMeta => const TaskConstMeta(
    debugName: "search_nodes",
    argNames: ["query", "limit"],
  );

  @override
  Future<String> crateApiSetupDatabase({
    required String contentDbPath,
    required String userDbPath,
    required List<int> kgBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(contentDbPath, serializer);
          sse_encode_String(userDbPath, serializer);
          sse_encode_list_prim_u_8_loose(kgBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSetupDatabaseConstMeta,
        argValues: [contentDbPath, userDbPath, kgBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetupDatabaseConstMeta => const TaskConstMeta(
    debugName: "setup_database",
    argNames: ["contentDbPath", "userDbPath", "kgBytes"],
  );

  @override
  Future<String> crateApiSetupDatabaseInMemory({required List<int> kgBytes}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(kgBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSetupDatabaseInMemoryConstMeta,
        argValues: [kgBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetupDatabaseInMemoryConstMeta =>
      const TaskConstMeta(
        debugName: "setup_database_in_memory",
        argNames: ["kgBytes"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AppState => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AppState => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ArcLearningService => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcLearningService;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ArcLearningService => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcLearningService;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ArcSessionService => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionService;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ArcSessionService => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionService;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ArcContentRepository => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynContentRepository;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ArcContentRepository => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynContentRepository;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ArcUserRepository => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynUserRepository;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ArcUserRepository => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynUserRepository;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  AppState
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AppStateImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ArcLearningService
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcLearningService(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArcLearningServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ArcSessionService
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionService(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArcSessionServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ArcContentRepository
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynContentRepository(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArcContentRepositoryImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ArcUserRepository
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynUserRepository(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArcUserRepositoryImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AppState
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AppStateImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AppState
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AppStateImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AppState
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AppStateImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ArcLearningService
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcLearningService(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArcLearningServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ArcSessionService
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionService(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArcSessionServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ArcContentRepository
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynContentRepository(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArcContentRepositoryImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ArcUserRepository
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynUserRepository(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArcUserRepositoryImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  DashboardStatsDto dco_decode_dashboard_stats_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DashboardStatsDto(
      reviewsToday: dco_decode_u_32(arr[0]),
      streakDays: dco_decode_u_32(arr[1]),
      dueCount: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  DebugStatsDto dco_decode_debug_stats_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DebugStatsDto(
      totalNodesCount: dco_decode_u_32(arr[0]),
      totalEdgesCount: dco_decode_u_32(arr[1]),
      dueCount: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  ExerciseDto dco_decode_exercise_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ExerciseDto(
      nodeId: dco_decode_String(arr[0]),
      question: dco_decode_String(arr[1]),
      answer: dco_decode_String(arr[2]),
      nodeType: dco_decode_String(arr[3]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<ExerciseDto> dco_decode_list_exercise_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_exercise_dto).toList();
  }

  @protected
  List<NodeSearchDto> dco_decode_list_node_search_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_node_search_dto).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SessionPreviewDto> dco_decode_list_session_preview_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_session_preview_dto).toList();
  }

  @protected
  List<SurahInfo> dco_decode_list_surah_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_surah_info).toList();
  }

  @protected
  NodeSearchDto dco_decode_node_search_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return NodeSearchDto(
      nodeId: dco_decode_String(arr[0]),
      nodeType: dco_decode_String(arr[1]),
      preview: dco_decode_String(arr[2]),
    );
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  SessionPreviewDto dco_decode_session_preview_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SessionPreviewDto(
      nodeId: dco_decode_String(arr[0]),
      nodeType: dco_decode_String(arr[1]),
      previewText: dco_decode_String(arr[2]),
      energy: dco_decode_f_64(arr[3]),
      priorityScore: dco_decode_f_64(arr[4]),
    );
  }

  @protected
  SurahInfo dco_decode_surah_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SurahInfo(
      number: dco_decode_i_32(arr[0]),
      name: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  AppState
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AppStateImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ArcLearningService
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcLearningService(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ArcLearningServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ArcSessionService
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionService(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ArcSessionServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ArcContentRepository
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynContentRepository(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ArcContentRepositoryImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ArcUserRepository
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynUserRepository(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ArcUserRepositoryImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AppState
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AppStateImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AppState
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AppStateImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AppState
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AppStateImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ArcLearningService
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcLearningService(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ArcLearningServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ArcSessionService
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionService(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ArcSessionServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ArcContentRepository
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynContentRepository(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ArcContentRepositoryImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ArcUserRepository
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynUserRepository(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ArcUserRepositoryImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  DashboardStatsDto sse_decode_dashboard_stats_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_reviewsToday = sse_decode_u_32(deserializer);
    var var_streakDays = sse_decode_u_32(deserializer);
    var var_dueCount = sse_decode_u_32(deserializer);
    return DashboardStatsDto(
      reviewsToday: var_reviewsToday,
      streakDays: var_streakDays,
      dueCount: var_dueCount,
    );
  }

  @protected
  DebugStatsDto sse_decode_debug_stats_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_totalNodesCount = sse_decode_u_32(deserializer);
    var var_totalEdgesCount = sse_decode_u_32(deserializer);
    var var_dueCount = sse_decode_u_32(deserializer);
    return DebugStatsDto(
      totalNodesCount: var_totalNodesCount,
      totalEdgesCount: var_totalEdgesCount,
      dueCount: var_dueCount,
    );
  }

  @protected
  ExerciseDto sse_decode_exercise_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nodeId = sse_decode_String(deserializer);
    var var_question = sse_decode_String(deserializer);
    var var_answer = sse_decode_String(deserializer);
    var var_nodeType = sse_decode_String(deserializer);
    return ExerciseDto(
      nodeId: var_nodeId,
      question: var_question,
      answer: var_answer,
      nodeType: var_nodeType,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<ExerciseDto> sse_decode_list_exercise_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ExerciseDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_exercise_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<NodeSearchDto> sse_decode_list_node_search_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NodeSearchDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_node_search_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SessionPreviewDto> sse_decode_list_session_preview_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SessionPreviewDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_session_preview_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<SurahInfo> sse_decode_list_surah_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SurahInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_surah_info(deserializer));
    }
    return ans_;
  }

  @protected
  NodeSearchDto sse_decode_node_search_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nodeId = sse_decode_String(deserializer);
    var var_nodeType = sse_decode_String(deserializer);
    var var_preview = sse_decode_String(deserializer);
    return NodeSearchDto(
      nodeId: var_nodeId,
      nodeType: var_nodeType,
      preview: var_preview,
    );
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SessionPreviewDto sse_decode_session_preview_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nodeId = sse_decode_String(deserializer);
    var var_nodeType = sse_decode_String(deserializer);
    var var_previewText = sse_decode_String(deserializer);
    var var_energy = sse_decode_f_64(deserializer);
    var var_priorityScore = sse_decode_f_64(deserializer);
    return SessionPreviewDto(
      nodeId: var_nodeId,
      nodeType: var_nodeType,
      previewText: var_previewText,
      energy: var_energy,
      priorityScore: var_priorityScore,
    );
  }

  @protected
  SurahInfo sse_decode_surah_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_number = sse_decode_i_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    return SurahInfo(number: var_number, name: var_name);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    AppState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AppStateImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcLearningService(
    ArcLearningService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ArcLearningServiceImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionService(
    ArcSessionService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ArcSessionServiceImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynContentRepository(
    ArcContentRepository self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ArcContentRepositoryImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynUserRepository(
    ArcUserRepository self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ArcUserRepositoryImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    AppState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AppStateImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    AppState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AppStateImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    AppState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AppStateImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcLearningService(
    ArcLearningService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ArcLearningServiceImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionService(
    ArcSessionService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ArcSessionServiceImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynContentRepository(
    ArcContentRepository self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ArcContentRepositoryImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynUserRepository(
    ArcUserRepository self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ArcUserRepositoryImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_dashboard_stats_dto(
    DashboardStatsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.reviewsToday, serializer);
    sse_encode_u_32(self.streakDays, serializer);
    sse_encode_u_32(self.dueCount, serializer);
  }

  @protected
  void sse_encode_debug_stats_dto(
    DebugStatsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.totalNodesCount, serializer);
    sse_encode_u_32(self.totalEdgesCount, serializer);
    sse_encode_u_32(self.dueCount, serializer);
  }

  @protected
  void sse_encode_exercise_dto(ExerciseDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.nodeId, serializer);
    sse_encode_String(self.question, serializer);
    sse_encode_String(self.answer, serializer);
    sse_encode_String(self.nodeType, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_exercise_dto(
    List<ExerciseDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_exercise_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_node_search_dto(
    List<NodeSearchDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_node_search_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_session_preview_dto(
    List<SessionPreviewDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_session_preview_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_surah_info(
    List<SurahInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_surah_info(item, serializer);
    }
  }

  @protected
  void sse_encode_node_search_dto(
    NodeSearchDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.nodeId, serializer);
    sse_encode_String(self.nodeType, serializer);
    sse_encode_String(self.preview, serializer);
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_session_preview_dto(
    SessionPreviewDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.nodeId, serializer);
    sse_encode_String(self.nodeType, serializer);
    sse_encode_String(self.previewText, serializer);
    sse_encode_f_64(self.energy, serializer);
    sse_encode_f_64(self.priorityScore, serializer);
  }

  @protected
  void sse_encode_surah_info(SurahInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.number, serializer);
    sse_encode_String(self.name, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class AppStateImpl extends RustOpaque implements AppState {
  // Not to be used by end users
  AppStateImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  AppStateImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_AppState,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_AppState,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_AppStatePtr,
  );

  ArcContentRepository get contentRepo => RustLib.instance.api
      .crateApiAppStateAutoAccessorGetContentRepo(that: this);

  ArcLearningService get learningService => RustLib.instance.api
      .crateApiAppStateAutoAccessorGetLearningService(that: this);

  ArcSessionService get sessionService => RustLib.instance.api
      .crateApiAppStateAutoAccessorGetSessionService(that: this);

  ArcUserRepository get userRepo =>
      RustLib.instance.api.crateApiAppStateAutoAccessorGetUserRepo(that: this);

  set contentRepo(ArcContentRepository contentRepo) =>
      RustLib.instance.api.crateApiAppStateAutoAccessorSetContentRepo(
        that: this,
        contentRepo: contentRepo,
      );

  set learningService(ArcLearningService learningService) =>
      RustLib.instance.api.crateApiAppStateAutoAccessorSetLearningService(
        that: this,
        learningService: learningService,
      );

  set sessionService(ArcSessionService sessionService) =>
      RustLib.instance.api.crateApiAppStateAutoAccessorSetSessionService(
        that: this,
        sessionService: sessionService,
      );

  set userRepo(ArcUserRepository userRepo) => RustLib.instance.api
      .crateApiAppStateAutoAccessorSetUserRepo(that: this, userRepo: userRepo);
}

@sealed
class ArcContentRepositoryImpl extends RustOpaque
    implements ArcContentRepository {
  // Not to be used by end users
  ArcContentRepositoryImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ArcContentRepositoryImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_ArcContentRepository,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_ArcContentRepository,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_ArcContentRepositoryPtr,
  );
}

@sealed
class ArcLearningServiceImpl extends RustOpaque implements ArcLearningService {
  // Not to be used by end users
  ArcLearningServiceImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ArcLearningServiceImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ArcLearningService,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ArcLearningService,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_ArcLearningServicePtr,
  );
}

@sealed
class ArcSessionServiceImpl extends RustOpaque implements ArcSessionService {
  // Not to be used by end users
  ArcSessionServiceImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ArcSessionServiceImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ArcSessionService,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ArcSessionService,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_ArcSessionServicePtr,
  );
}

@sealed
class ArcUserRepositoryImpl extends RustOpaque implements ArcUserRepository {
  // Not to be used by end users
  ArcUserRepositoryImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ArcUserRepositoryImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ArcUserRepository,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ArcUserRepository,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_ArcUserRepositoryPtr,
  );
}
